ALTER SESSION SET "_ORACLE_SCRIPT"=true;
DROP USER USUARIO_NUEVO CASCADE;
CREATE USER USUARIO_NUEVO IDENTIFIED BY "PASSWORD"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER USUARIO_NUEVO QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO USUARIO_NUEVO;
GRANT "RESOURCE" TO USUARIO_NUEVO;
ALTER USER USUARIO_NUEVO DEFAULT ROLE "RESOURCE";